### ISSUE TITLE
The password was not accepted

### ISSUE THREAD

**Issue by fmastr1** [Ezzpify/HourBoostr#22]
![prueba](https://cloud.githubusercontent.com/assets/20672252/17159811/a7072d0e-5376-11e6-91c5-ac7b55aa708d.jpg)

**Comment by Truth91** [comment]
getting the same issue here with the newest build available. it was working fine about 2 hours ago.

**Comment by MrFurison** [comment]
I do not know who to work, but in my Amazon does not work!

**Comment by Doniiii** [comment]
I believe this is because there is currently no CD on the new build if you login elsewhere. The bot keeps trying to connect to the Steam server over and over resulting in a cooldown because of the spam. If you are planning to use the bot and play at the same time elsewhere I would recommend you to download the older version that has a cooldown system in place.

**Comment by Ezzpify** [comment]
I'm re-implementing the cooldown system that existed in the previous version like @Doniiii said. As for now, just close the bot before you start playing games on your pc.
