### ISSUE TITLE
Account not going online

### ISSUE THREAD

**Issue by nicopxxch** [Ezzpify/HourBoostr#43]
Hey my account is not going online/appearing online. 

Log:
[28.10.2016 11:50:18] Info: Connecting to Steam ...
[28.10.2016 11:50:18] Info: Connected! Logging in ...
[28.10.2016 11:50:19] Success: Successfully logged in!
[28.10.2016 11:50:19] Info: 1 has been set as playing.

Settings are:
"ShowOnlineStatus": true,
"ConnectToSteamCommunity": true

Any help?

**Comment by Sufex1234** [comment]
I've been currently having the same problem, may i add that it is extremely annoying when after you've finished idling and close the program your steam is still displaying that you cannot connect to the friends network so you have to constantly restart steam. Lastly, you cannot play games whilst this offline feature is enabled so at this point im thinking if this hourboostr is really usefull or not, because im not going to spend my whole idling time doing nothing.

**Comment by Ezzpify** [comment]
Are you online on the steam client at the same time?

**Comment by Firefly1029** [comment]
@Ezzpify if I run the bot then sign on it stops idling that account but leaves me in offline mode. So I have to restart steam and if I want to idle other accounts I have to remove the account I want to use from the booster. Is there a way around this.
