### ISSUE TITLE
Forced Offline Mode

### ISSUE THREAD

**Issue by Revolx** [Ezzpify/HourBoostr#49]
Hey so i have been having the issue to where i want to appear online on steam, (Able to still use chat window/Friends list) but have the idle running. When i try change my "status" on steam to "Online" nothing happens forcing me to restart my client. 

The idle is still running but unable to use my steam for anything during idle.

Fix? 

{
  "HideToTrayAutomatically": false,
  "CheckForUpdates": true,
  "Accounts": [
    {
      "Details": {
        "Username": "*Replaced to protect information*",
        "Password": "*Replaced to protect information*",
        "LoginKey": ""
      },
      "ShowOnlineStatus": true,
      "ConnectToSteamCommunity": true,
      "RestartGamesEveryThreeHours": true,
      "JoinSteamGroup": false,
      "ChatResponse": "",
      "Games": [
        385200,
        326190
      ]
    }
  ]
}

"A connection to the Friends network could not be established. Steam will automatically retry connection until the services become available." - Message on Steam Friends Chat Box

Why is this happening?

**Comment by Sufex1234** [comment]
I've been currently having the same problem, may i add that it is extremely annoying when after you've finished idling and close the program your steam is still displaying that you cannot connect to the friends network so you have to constantly restart steam. Lastly, you cannot play games whilst this offline feature is enabled so at this point im thinking if this hourboostr is really usefull or not, because im not going to spend my whole idling time doing nothing.

**Comment by Ezzpify** [comment]
Hello! Please check out the new SingleBoostr program included in the HourBoostr download.
It will let you use the same account you're logged into the Steam client with.
